zenoss/ZenPacks.zenoss.LinuxMonitor

ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

ZEN-20794
This reverts a change made previously to the rpn formula.  The previous change resulted in the graph displaying % available instead of % used.  Reverting this change results in the graphs displaying the correct values.

Linux using SSH - Block Utilization for File System has wrong value

---

ZenPacks/zenoss/LinuxMonitor/SnapshotVolume.py
ZenPacks/zenoss/LinuxMonitor/configure.zcml
ZenPacks/zenoss/LinuxMonitor/openstack_cinder.py

ZEN-22158
* change class name CephCinderImplementationPlugin
to to LinuxCinderImplementationPlugin
* fixed class names in class LinuxCinderImplementationPlugin,
method reindex_implementation_components()

Take underscore out if there is one in snapshotname.

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

The cmd.linux.lvm modeler plugin was running "lsblk -lb" to capture
information about all block devices. Block devices with very long names
like the following created by docker thin pool usage result in each
block device entry being split into two lines. Using "lsblk -rb" to use
raw instead of list formatting fixes it.
Fixes ZEN-22253.

Fix LVM modeling IndexError on long lsblk lines.

---

ZenPacks/zenoss/LinuxMonitor/__init__.py
ZenPacks/zenoss/LinuxMonitor/patches/__init__.py
ZenPacks/zenoss/LinuxMonitor/patches/platform.py

This ZenPack makes heavy use of overridding component.getGraphObjects()
to show useful graphs from related contexts for many component types.
Currently this isn't well-supported by the platform. All of the
other-contexted graph definitions will appear as choices in the graph
selection when the component type is selected. If any of these
other-contexted graphs are chosen, no data will be displayed on the
graphs.
This monkeypatch fixes the platform to filter out other-contexted graph
definitions, but only for Linux devices.
Fixes ZEN-22254.

Fix "Component Graphs" for custom getGraphObjects

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/lvsstatus.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

When the lvsstatus parser was written, LogicalVolume and SnapshotVolume
ids were just "<vgname_lvname>" which matched the output of the lvs
command being run for this parser. Now we're prefixing LV ids with "lv-"
so the match no longer works.
This change simplies the command being run by removing awk pre-parsing
and letting the lvsstatus parser do all the parsing work by specifically
matching the VG name and LV name in the output columns with the VG name
and LV name of each LogicalVolume and SnapshotVolume.
Fixes ZEN-22301.

Fix lvsstatus parser now that LV ids are prefixed

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Restored the following datapoint aliases:
* usedFilesystemSpace_bytes (used by Filesystem Util Report)
* loadAverage5min (used by CPU Utilization report)
* inputOctets__bytes (used by Interface Utilization report)
* outputOctets__bytes (used by Interface Utilization report)
* memoryBuffered__bytes (used by Memory Utilization report)
* memoryCached__bytes (used by Memory Utilization report)
* memoryAvailable__bytes (used by Memory Utilization report)
* memoryUsed__pct (used by Memory Utilization report)
There's still a big problem with all of these performance reports. It
appears that the datapoint alias RPN formulas are not being calculated
at all. So the while this fix makes numbers appear, most of them are
completely wrong. This appears to be a platform issue in …

Restore aliases used by performance reports

---

ZenPacks/zenoss/LinuxMonitor/LinuxDevice.py
ZenPacks/zenoss/LinuxMonitor/parsers/Standard.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Reduce all /Cmd/Fail events resulting from SSH connectivity failures
into a single event indicating what the nature of the connectivity
failure. I wanted to make this event a /Status/SSH event with a critical
severity, but zencommand doesn't allow us that kind of flexibility.
To keep things clean going forward we need to make sure our COMMAND
datasources use the /Ignore event class and clear severity so they don't
generate their own /Cmd/Fail events. Let the 60 second cycletime
Device/ssh datasource deal with reporting SSH connectivity failures.
Fixes ZEN-20498.

Consolidate events when SSH connectivity fails

---

ZenPacks/zenoss/LinuxMonitor/patches/__init__.py
ZenPacks/zenoss/LinuxMonitor/patches/twistedConch.py

Created for Twisted (13.2.0)
Based on the following patches:
1) http://twistedmatrix.com/trac/attachment/ticket/7717/7717-v10.patch
2) http://twistedmatrix.com/trac/attachment/ticket/7672/dhgex-sha256-4.patch
Unit tests have not been monkeypatched.
Ubuntu 15, auth.log:
Before monkeypatching - https://gist.github.com/itshane/0de35c459284f6e9c026
After monkeypatching - https://gist.github.com/itshane/9f3b5cb5f6c905f28b71
The changes have been successfully tested on:
Ubuntu 12.04.1 LTS
Ubuntu 14.04.4 LTS
Ubuntu 15.04
CentOS release 5.8 (Final)
CentOS release 6.5 (Final)
CentOS Linux release 7.1.1503 (Core)
Debian GNU_Linux 7 (wheezy)

fixes ZEN-21774: Algorithm negotiation fail with openSSH version 6.7.

---

ZenPacks/zenoss/LinuxMonitor/__init__.py

Now that the /Server/SSH/Linux device class is owned by this ZenPack, it
must add the Linux Server (SSH) devtype. This devtype information is
used by the device add/discovery wizard to give users an easier to use
list of possible device types to add than the entire device class
hierarchy.
Fixes ZEN-22359.

Add Linux Server (SSH) device type on install

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

* Aliases for datapoints as defined by ZEN-12911.
* Aliases for all LVM component datapoints.
Fixes ZEN-12911.

Add datapoint aliases.

---

ZenPacks/zenoss/LinuxMonitor/zenpacklib.py

Now some component types will have a Dynamic View option and some won't.
The new LVM components will have Dynamic View available.
* Physical Volume
* Volume Group
* Logical Volume
* Snapshot Volume
Standard type components won't have Dynamic View.
* OS Process
* File System
* Hard Disk
* Network Interface
Fixes ZEN-21669.

Upgrade to zenpacklib 1.0.11 to fix Dynamic View

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

There are a couple of issues (ZEN-22411 and ZEN-22413)  with Component
Graphs in Zenoss 5.1.1 that cause them not work when a graph point's RPN
refers to another graph point. We used this feature for PhysicalVolume
and VolumeGroup Utilization graphs.
To workaround the issue we use a TALES expression to get the current
size of the given PV/VG instead. This seems to work, but is not as good
in the long run because it doesn't accomodate for the size of the volume
changing over time as well.
Fixes ZEN-22254.

Workaround "All on Same Graph?" issue for PV/VG

---

ZenPacks/zenoss/LinuxMonitor/FileSystem.py
ZenPacks/zenoss/LinuxMonitor/LogicalVolume.py
ZenPacks/zenoss/LinuxMonitor/PhysicalVolume.py
ZenPacks/zenoss/LinuxMonitor/SnapshotVolume.py
ZenPacks/zenoss/LinuxMonitor/VolumeGroup.py
ZenPacks/zenoss/LinuxMonitor/util.py

Fixes ZEN-22543.
* Override getDefaultGraphDefs()
* Make all graph['title'] uniq

Explicitly label graphs for 4.X making labels uniq

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fixes ZEN-22544.
* Old command didn't always have path to ifconfig command.
* Used /usr/bin/env PATH=/sbin:/usr/sbin ifconfig -a

Reformulate commandTemplate for ethernetCsmacd

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py

Fixes ZEN-22568
* Fixed bug in os_service logging (debug mode). Getting Traceback: rm is not
type of object that logging can handle. Resulted in Traceback in debug mode.

Fix OS Process in modeler

---

ZenPacks/zenoss/LinuxMonitor/util.py

Fixes ZEN-22593
Some imported graphs have excessively long titles that
were pushing the buttons out of range.

Truncate title strings in overridden graphs to 34

---

README.mediawiki

Fixes ZEN-22639
* Use wildcards sudo command to allow for xargs sudo
* This is secure because first commands limit use to listing.

Add documentation on sudoers for modeler

---

ZenPacks/zenoss/LinuxMonitor/util.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fixes ZEN-22593
* Reduced 4x imported graph title UUIDs and name prefix
* Change one graph title to make room

Reduce size of title so it fits on graph

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

Fixes ZEN-22639
* Reformat wiki documentation to make more legible
* Add in docs for more robust /etc/sudoers
* Add needed PATH export for modeler/plugins/zenoss/cmd/linux/lvm.py

Ensure modeling on Centos5, Suse 12

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/cpu.py
ZenPacks/zenoss/LinuxMonitor/parsers/linux/mem.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

These datapoints have long been needed for easier thresholding and usage
of basic Linux performance monitoring in higher-level reports. No more
will we need RPNs like "100,EXC,-,0,MAX" or
"${here/hw/totalMemory},/,1,-,100,*,ABS" just to figure out what CPU and
memory utilization are.
Fixes ZEN-22978.

Add cpu_ssCpuUsedPerCpu and mem_MemUsedPercent

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

IO Throughput graph's Written datapoint has been updated with a custom color.

Fixes ZEN-18605.

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Previously we were assuming interfaces without a known speed were
10Mbps. This seems like a really bad guess, and as of 29d94c9 we are
much better able to determine the speed of interfaces.
This change to assume a 1Tbps interface speed in the absence of a known
speed is intended to prevent any threshold violations on interfaces for
which we still don't know the speed. This would apply to special
interface types like bridges. For bridges we're getting usage and speed
from the member interfaces anyway.

Prevent thresholds on NICs with unknown speed

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

/Perf/FileSystem is not an event class that will exist. It should be
/Perf/Filesystem instead. This will result in a broken link from the
event console's event class column when the event is generated. It will
also result in nothing being chosen in the threshold's event class
field when edited.

Fix typo in /Perf/Filesystem threshold

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

For devices that may have hundreds of unmounted disks, there is no need to model/monitor them.
Cherry picked from 58854054b593c20e455772cfc4168538e8b636d6 to get into a hotfix

Add zIgnoreUnmounted property to ignore unmounted hard disks

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/migrate/NewDeviceType.py
ZenPacks/zenoss/LinuxMonitor/tests/test_NewDeviceType.py
ZenPacks/zenoss/LinuxMonitor/tests/utils.py

Instead of moving the devices to have them deleted and recreated with
the new type, we'll just set the __class__ of the existing devices and
call buildRelations on them. This is about 100,000 times faster on my
system with test devices that have 400 components each.
Fixes ZEN-24024.

Optimize NewDeviceType migration

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/migrate/NewDeviceType.py

The NewDeviceType migration optimization (8a311e2) seems to fail in
changing the class of Linux devices from Device
(Products.ZenModel.Device.Device) to LinuxDevice
(ZenPacks.zenoss.LinuxMonitor.LinuxDevice.LinuxDevice) due to ZODB not
storing the change to the device's __class__ attribute. It appears that
the change is successful, but upon reloading the Zope client, __class__
is reset back to its original value.
This is apparently a known behavior of ZODB, but there is a workaround.
This commit uses that workaround to also replace the object's persistent
reference and cause the __class__ change to be permanent.
Fixes ZEN-24293.

Fix NewDeviceType migration

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/patches/__init__.py

The patch is backporting changes from Twisted 15. So there's no reason
to do it if the platform already includes Twisted 15.
Refs ZEN-23392.

Only patch Conch on Twisted earlier than 15

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Added the following datapoint alises for all applicable datapoints.
- mem__pct
- fs__pct
- in__pct
- out__pct
Refs ZEN-24619.

Add common datapoint aliases

---

ZenPacks/zenoss/LinuxMonitor/tests/plugindata/lvm
ZenPacks/zenoss/LinuxMonitor/tests/test_dvi.py

No problems in the code being tested. Just problems in the unit tests.
- testPlugins failed due to a slight change in the command being run.
- TestDVI was expecting DynamicView and Impact to be installed.
These tests have already been fixed on the develop branch. Fixing them
again in a hotfix so we can keep Zenoss 5.2 tests passing with a stable
version of LinuxMonitor.
ZEN-24653 will only be fixed once LinuxMonitor 2.0.5 is released with
this fix.

Fix testPlugins and TestDVI unit tests

---

README.mediawiki
ZenPacks/zenoss/LinuxMonitor/tests/testLVMParser.py
ZenPacks/zenoss/LinuxMonitor/util.py

Fixes ZEN-25792
RHEL 6.3 has an older version of lvs that does not emit the
health attribute.  Added unit test for the parser

Fix IndexError for older versions of lvs

---

ZenPacks/zenoss/LinuxMonitor/tests/test_NewDeviceType.py
ZenPacks/zenoss/LinuxMonitor/tests/test_dvi.py

- Fixes ZEN-26151
- Updated imports for TestCase and others
- Enable tests to run from command line

Update Unit tests to support ZPL2 (ZEN-26151)

---

ZenPacks/zenoss/LinuxMonitor/tests/test_NewDeviceType.py
ZenPacks/zenoss/LinuxMonitor/tests/test_dvi.py

Fixes ZEN-26200
TestCase has been added back to zpl2 for backwards compatibility.

Fix unit test missing module name

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/alt_kernel_name.py

Found that customized etc issue with an MOTD style message cause errors:
File "/opt/zenoss/lib/python2.7/site-packages/OFS/ObjectManager.py", line 105, in checkValidId
'The id "%s" is invalid because it ends with two underscores.' % id)
BadRequest: The id "Red Hat Enterprise Linux Server release 6.5 (Santiago)_Kernel _r on an _m___________________________________________________________________________________                                                                         _____ This computer system is for authorized use only.  Users (authorized or  _____ unauthorized) have no explicit or implicit expectation of privacy.  Any _____ or all use of this system and all files on this system may be           _____ intercepted, monitored, recorded, copied, audited, inspected and …

Remove lines starting with #

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/interfaces.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fixes ZEN-25425
Some installations can have both ifconfig and ip addr.  We should
be using ip addr before ifconfig as ifconfig can show bad results

Use 'ip addr' command before ifconfig

---

ZenPacks/zenoss/LinuxMonitor/HardDisk.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fixes ZPS-939
If the link to the storage disk/lun can be found, add the link
to hard disk details.

Add link to storage disk/lun for hard disk

---

README.rst

The README advises removing the EnterpriseLinux ZenPack but is not specific about when to remove it. This has resulted in the EnterpriseLinux ZenPack being removed before the new LinuxMonitor ZenPack has been loaded, causing removal of /Server/SSH/Linux devices/

Update README.rst to prevent confusion

---

ZenPacks/zenoss/LinuxMonitor/FileSystem.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/df.py

- Fixes ZPS-1312
- Remove getTotalBlocks() method override from FileSystem, which was
providing the total as (used + avail) perf metric instead of modeled
value
- Update df.py modeler plugin to use (avail + used) where total blocks
is not available in the output

Reduce unnecessary QueryService calls (ZPS-1312)

---

README.rst
ZenPacks/zenoss/LinuxMonitor/FileSystem.py
ZenPacks/zenoss/LinuxMonitor/tests/test_FileSystem.py

Previously the FileSystem.type had to be exactly "nfs". Now anything
that starts with "nfs" such as "nfs4" will also use the NFS template. I
also made the match case-insensitive.
Fixes ZPS-1495.

Use FileSystem_NFS_Client template for all NFS

---

README.rst
ZenPacks/zenoss/LinuxMonitor/FileSystem.py
ZenPacks/zenoss/LinuxMonitor/migrate/UpdateFileSystemTransform.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/df.py
ZenPacks/zenoss/LinuxMonitor/resources/device.js
ZenPacks/zenoss/LinuxMonitor/tests/test_modeler_df.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Attempting to calculate our own capacity value that matched the
"Capacity" column in Linux's df output turns out to be pretty much
impossible due to the various per-filesystem special reservations that
can make used + available != total.
This change takes what I hope is the simplest and best approach to
addressing this complication. We'll just collect and use the "Capacity"
column from df's output in all of the places where people expect that
value.
- Add percentUsed datapoint to filesystems
- Use percentUsed datapoint in Utilization graph
- Use percentUsed datapoint in default "90 percent used" threshold
- Use percentUsed in /Perf/Filesystem event transform
See ZPS-1545 for more detail on the problems that this change addresses.
Fixes ZPS-1545.

Fix inconsistencies with our data and df's output

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/df.py
ZenPacks/zenoss/LinuxMonitor/tests/plugindata/df
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

The previous fix for this issue (8840154) only wrapped the "df" command
within the FileSystem_NFS_Client monitoring template with a timeout.
This didn't help much because the same command was still being run from
the regular FileSystem monitoring template, and from the
zenoss.cmd.linux.df modeler plugin.
This update handles those two cases as well. This should prevent orphan
"df" command ever being left running on the target Linux server when it
is having timeouts reaching its NFS servers.
Furthermore the regular FileSystem monitoring template was updated to
use df's "-l" argument to limit it to only local filesystems. This means
we don't have to wrap it in a timeout at all, and it allows monitoring
of local filesystems to continue successfully even when NFS-mounted
filesystems timeout. …

Guard all "df" commands against NFS timeout

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

It turns out that df's -l flag will also exclude some devicemapper
mounts. I tried using "df -kP -x nfs" to exclude NFS filesystems, but it
appears that df's -x and -t flags are only checked after the code that
results in a timeout, because "df -kP -x nfs" will also hang if there's
a hung NFS mount.
Fixes ZPS-1816.

Set a timeout on local filesystem monitoring too

---

ZenPacks/zenoss/LinuxMonitor/resources/device.js

The custom renderer used for the filesystem "Storage Device" column
assumed that the storage device would be a component on the same device
such as a HardDisk or LogicalVolume component. In cases such as this
where the storage device is a NetApp FileSystem mounted via NFS, this
assumption breaks.
Updated the custom renderer to use a same-device link if the storage
device is on the same device as the filesystem, and to use a regular
link otherwise.
Fixes ZPS-1822.

Fix NoneType flare when clicking Storage Device

---

ZenPacks/zenoss/LinuxMonitor/tests/test_NewDeviceType.py

The nature of this test is that it fails when it takes too long. This
has caused at least one build to fail when it shouldn't have. Disabling
the test since it's non-deterministic.
Fixes ZPS-1827.

Disable non-deterministic test_ten_devices test

---

README.rst
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Because the commandTemplate on these COMMAND datasources didn't begin
with a / (forward slash), zencommand would prefix the entire command
with the device's zCommandPath value, which is $ZENHOME/libexec by
default. This resulted in zencommand log messages like the following.
WARNING zen.SshClient: <ip-address> channel 450 The command $ZENHOME/libexec/export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin; if command -v timeout > /dev/null 2>&1; then timeout 30 /usr/bin/env df -ikP; else /usr/bin/env df -ikP; fi returned stderr data (1) from the device: bash: /libexec/export: No such file or directory
It appears this didn't prevent monitoring from working because only the
export resulted in an error, and the other commands continued to
execute, and their output was parsed.
Fixes ZPS-1823.

Fix zencommand warnings monitoring NFS filesystems

---

README.rst
ZenPacks/zenoss/LinuxMonitor/parsers/linux/mem.py
ZenPacks/zenoss/LinuxMonitor/tests/parserdata/linux/leak.zenoss.loc/mem.py
ZenPacks/zenoss/LinuxMonitor/tests/parserdata/linux/linux-2.4/mem.py
ZenPacks/zenoss/LinuxMonitor/tests/parserdata/linux/linux-4.4.0/mem
ZenPacks/zenoss/LinuxMonitor/tests/parserdata/linux/linux-4.4.0/mem.py

MemAvailable exists in newer kernels, and the difference between
MemTotal and MemAvailable is a more useful indicator of how much memory
is actively being used on a a system than the difference between
MemTotal and MemFree.
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773
The intention of 05269b2 was to do this, but the combination of the mem
parser's code, and the lack of a MemAvailable datapoint on the mem
datasource resulted in MemFree still being used. This change corrects
that by not requiring a MemAvailable datapoint to exist.
Fixes ZPS-1144.

Use MemAvailable instead of MemFree for Used %

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/interfaces.py

Fixes ZPS-1933
* Also is backward compatible with older systems.

Allow for restricted /bin/dmesg access in Debian9

---

ZenPacks/zenoss/LinuxMonitor/HardDisk.py
ZenPacks/zenoss/LinuxMonitor/configure.zcml
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fixes ZPS-2905.
* Update HardDisk.storage_disk_lun method to find storage providers with 'has-target-wwn' ids
* Add HardDisk.disk_ids to searchKeywords
* Update impact for HardDisk components

Update links to storage providers for HardDisk components

---

README.rst
ZenPacks/zenoss/LinuxMonitor/LinuxService.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py
ZenPacks/zenoss/LinuxMonitor/parsers/linux/service.py
ZenPacks/zenoss/LinuxMonitor/tests/testOSServiceTemplates.py
ZenPacks/zenoss/LinuxMonitor/tests/test_serviceParser.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fixes ZPS-3442
After redesign of sysV systems, sysD monitoring breaks and places
zencommand in an infinite loop. To resolve this, we split monitoring
code to three different templates that bind to a linux device based
on their init_system which we set during modeling. Other things fixed:
- enabled unit tests for sysV
- fix additional sysV monitoring code

Split Service templates per init System

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/ps.py

Process restart events were using the datasource's configured severity
which is 0 (clear) to work around spam events zencommand would otherwise
send for other conditions.
We should be using zFailSeverity from the process' process class just
like we do for process down events.
Fixes ZPS-1508.

Fix clear severity on process restart events

---

README.rst
ZenPacks/zenoss/LinuxMonitor/__init__.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py
ZenPacks/zenoss/LinuxMonitor/tests/testOSServicePlugin.py

Update regex to capture UnitFileState when blank, full word (e.g. "enabled") and word with hyphen (e.g. "enabled-runtime"). Also updated unit tests to support regex update.

Update regex to match blank unitFileState service

---

README.rst
ZenPacks/zenoss/LinuxMonitor/LinuxService.py
ZenPacks/zenoss/LinuxMonitor/__init__.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py
ZenPacks/zenoss/LinuxMonitor/tests/testOSServiceTemplates.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

In LinuxMonitor 2.3.0 we began monitoring Linux services. There were
some problems in how we decided which services to model that resulted in
services that weren't supposed to be running (disabled in some way)
being modeled, and then being monitored. These services would flood the
system with events about services that were supposed to be down being
down.
We corrected this in LinuxMonitor 2.3.1, but in the process we added the
sudo execution of new commands to the cmd.linux.os_service modeler
plugin. This has had the result of making modeling fail for environments
where the sudo configuration was locked down to the previous set of sudo
commands. This modeling failure causes the erroneously-modeled "supposed
to be down" services to remain modeled, which results in monitoring
continuing, …

Prevent monitoring of potentially wrong services

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/df.py
ZenPacks/zenoss/LinuxMonitor/tests/plugindata/df
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

We'll try first with sudo, and if that fails, we'll try without sudo.
This will allow for a seamless transition for users that are upgrading
from LinuxMonitor < 2.3.0 who have not updated their sudoers
configuration to allow df to be run via sudo.
Fixes ZPS-4340.

Allow df to work with or without sudo

---

README.rst
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

The zenoss.cmd.linux.lvm modeler plugin models all LVM components.
- Hard Disks
- Physical Volumes
- Volume Groups
- Logical Volumes
- Thin Pools
The modeler plugin first sets the path to `/bin:/sbin:/usr/bin:/usr/sbin`
before running its various commands. This allows modeling to work even
when zCommandUser's PATH doesn't contains the commands. Monitoring
doesn't preset the same PATH, so monitoring of the modeled components
can fail when zCommandUser's PATH doesn't contain the commands.
This fix sets the same PATH during monitoring as it set during modeling
so this discrepancy can't occur.
Fixes ZPS-4349.

Fix LVM monitoring when */sbin not in PATH

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py
ZenPacks/zenoss/LinuxMonitor/parsers/linux/service.py
ZenPacks/zenoss/LinuxMonitor/tests/test_serviceParser.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

The "systemctl list-units" and "systemctl show" commands we're now using
don't require sudo to execute. So we can stop asking users to include
any systemd (systemctl) commands in their sudoers configuration.
Fixes ZPS-4121.

Stop using sudo for systemd service monitoring

---

ZenPacks/zenoss/LinuxMonitor/HardDisk.py

These changes fix the following uncorroborated impact relationships
reported by Impact's check-providers.py tool.
INFO:zen.ProviderChecker:DSVRelationshipProvider(puffer/disk-data-z) provides uncorroborated impact: puffer/z
INFO:zen.ProviderChecker:DSVRelationshipProvider(puffer/lv-data_z) provides uncorroborated impacted-by: puffer/disk-data-z
Fixes ZPS-5711.

fix uncorroborated impact relationships

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

When modeling "disk_ids" that can be used to correlate disks to their
underlying storage provider, we try to pick serial numbers out. However,
there was a particularly greedy case that looked at Ubuntu swap disks
like "disk-qa--ubuntu--12-swap_1" and picked off the last "1" as a
serial number. We then search for any components in the system that have
"1" as a keyword and say that they impact us. This is definitely not a
good thing.
This change attempts to keep the behavior as close as possible to what
was originally intended while avoiding overly-simple keywords by
expecting serial numbers to have over 12 characters. The test data we
have for this feature shows only serial numbers 18 or more characters.
Fixes ZPS-5792.

fix disks being impacted by random objects.

---

ZenPacks/zenoss/LinuxMonitor/tests/test_dynamicview.py

This change fixes a unit test failure that will occur when the
OpenStackInfrastructure ZenPack is installed. There's a bug in that
ZenPack that assumes there will always be a /OpenStack/Infrastucture
device class, but there isn't in the test sandbox.
Fixes ZPS-5799.

fix OpenStack-related unit test failure

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

Using an undefined variable can result in a traceback like the following
when modeling systems with LVM.
2019-05-17 13:24:42,458 ERROR zen.ZenModeler: Traceback (most recent call last):
File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 670, in processClient
datamaps = plugin.process(device, results, self.log)
File "/mnt/src/ZenPacks.zenoss.LinuxMonitor/ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py", line 244, in process
hd_om.disk_ids.append(parts[-1])
NameError: global name 'parts' is not defined
Fixes ZPS-5815.

fix modeling traceback introduced in c24bbc0

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

We have no snapshotVolumes relationship on thin pools, yet the
zenoss.cmd.linux.lvm modeler plugin was trying to set it. This resulted
in tracebacks like the following when modeling.
2019-05-17 13:56:27,388 INFO zen.ZenModeler: plugins: zenoss.cmd.linux.lvm
2019-05-17 13:56:27,388 INFO zen.ZenModeler: SNMP monitoring off for puffer
2019-05-17 13:56:27,390 INFO zen.ZenModeler: No portscan plugins found for puffer
2019-05-17 13:56:27,814 INFO zen.CmdClient: command client finished collection for puffer
2019-05-17 13:56:28,015 ERROR zen.ZenModeler: : Traceback (most recent call last):
File "/opt/zenoss/Products/ZenHub/PBDaemon.py", line 109, in inner
return callable(*args, **kw)
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 163, in remote_applyDataMaps
if …

fix "NotFound: tp-*" traceback modeling thin pools

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

In commit c24bbc0 I changed the modeler plugin to require that serial
numbers in disk IDs must be longer than 12 characters. It turns out that
this was too long. A drive serial number of "9XG56VGD" was found. So I'm
lowering that limit to include serial numbers longer than 7 characters.
Fixes ZPS-5828.

fix UCS disk impact regression in c24bbc0

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py
ZenPacks/zenoss/LinuxMonitor/tests/plugindata/lvm.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fixes ZPS-6103.
Renamed components' UUID property to more specific to avoid conflict. 
Fixed existing unit tests.

Fixed LVM components representation on Smart View

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/ifconfig.py

Fixes ZPS-8020.
A fix for the OSs that provide "missed" column
instead of "overrun" in the ifconfig output.

Add "missed" column to the ifconfig scanners
