ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

Fixes https://jira.zenoss.com/browse/ZEN-21167

ZEN-21167: Show percentage of used inodes on Y-axis

---

ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

Linux using SSH - Block Utilization for File System has wrong value

---

ZenPacks/zenoss/LinuxMonitor/__init__.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml
ZenPacks/zenoss/LinuxMonitor/zenpacklib.py

convert linux to use zepacklib.  add modeler plugin for lvm

add lvm modeler, convert to zenpacklib

---

ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

jira ticket https://jira.zenoss.com/browse/ZEN-21670

fix ZEN-21670, view graph IO for device

---

ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

https://jira.zenoss.com/browse/ZEN-21648

fix ZEN-21648

---

ZenPacks/zenoss/LinuxMonitor/configure.zcml
ZenPacks/zenoss/LinuxMonitor/impact.py

https://jira.zenoss.com/browse/ZEN-15251

fix ZEN-15251

---

ZenPacks/zenoss/LinuxMonitor/LogicalVolume.py
ZenPacks/zenoss/LinuxMonitor/SnapshotVolume.py
ZenPacks/zenoss/LinuxMonitor/configure.zcml
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py
ZenPacks/zenoss/LinuxMonitor/openstack_cinder.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

ZEN-21762: LVM OpenStack integration.

---

ZenPacks/zenoss/LinuxMonitor/migrate/INodeUtilizationGraph.py
ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

https://jira.zenoss.com/browse/ZEN-8204

fix ZEN-8204

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-21729

fix ZEN-21729

---

ZenPacks/zenoss/LinuxMonitor/configure.zcml
ZenPacks/zenoss/LinuxMonitor/openstack_cinder.py

Fix import issue via configure.zcml

---

ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

https://jira.zenoss.com/browse/ZEN-21772

fix ZEN-21722

---

ZenPacks/zenoss/LinuxMonitor/objects/objects.xml

https://jira.zenoss.com/browse/ZEN-12911

add aliases to excisting datapoints according to ticket ZEN-12911

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-22184

fix ZEN-22184

---

ZenPacks/zenoss/LinuxMonitor/browser/resources/js/global.js

https://jira.zenoss.com/browse/ZEN-22217

fix ZEN-22217

---

ZenPacks/zenoss/LinuxMonitor/FileSystem.py
ZenPacks/zenoss/LinuxMonitor/HardDisk.py
ZenPacks/zenoss/LinuxMonitor/LogicalVolume.py
ZenPacks/zenoss/LinuxMonitor/PhysicalVolume.py
ZenPacks/zenoss/LinuxMonitor/info.py
ZenPacks/zenoss/LinuxMonitor/interfaces.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py
ZenPacks/zenoss/LinuxMonitor/parsers/linux/diskstats.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://rally1.rallydev.com/#/14634827648d/detail/task/51681621737

add monitoring templates for Hard Disk component, implement TA27767

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/pvvgstats.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-22148

fix ZEN-22148

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_release.py

https://jira.zenoss.com/browse/ZEN-22218

fix ZEN-22218

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/cpuinfo.py

https://jira.zenoss.com/browse/ZEN-21665

fix ZEN-21665

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Drop autoscaling for all "percent" graphpoints

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/diskstats.py
ZenPacks/zenoss/LinuxMonitor/tests/plugindata/cpuinfo.py

https://jira.zenoss.com/browse/ZEN-15701

fix ZEN-15701

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fix legend formatting for Memory Usage graph

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/lvsstatus.py

Handle older Linux kernels' lv_attr format

---

ZenPacks/zenoss/LinuxMonitor/__init__.py

https://jira.zenoss.com/browse/ZEN-22388

fix ZEN-22388

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-22506

fix ZEN-22506

---

ZenPacks/zenoss/LinuxMonitor/LinuxDevice.py
ZenPacks/zenoss/LinuxMonitor/configure.zcml
ZenPacks/zenoss/LinuxMonitor/impact.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-22482

fix ZEN-22482

---

ZenPacks/zenoss/LinuxMonitor/LinuxDevice.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-22511

fix ZEN-22511

---

ZenPacks/zenoss/LinuxMonitor/FileSystem.py

https://jira.zenoss.com/browse/ZEN-22542

fix ZEN-22542

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

https://jira.zenoss.com/browse/ZEN-22552

fix ZEN-22552

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py

https://jira.zenoss.com/browse/ZEN-22568

fix ZEN-22568

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-22606

made shorter label for Merge Rate graph; fixes ZEN-22606

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

remove Dynamic View from combobox on  Linux Service component

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

https://jira.zenoss.com/browse/ZEN-22673

add default values to properties; fix ZEN-22673

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

Makes the existing lvm regex expressions more rigorous.

---

ZenPacks/zenoss/LinuxMonitor/migrate/updateNovaHostPlugins.py

https://jira.zenoss.com/browse/ZEN-23151

fix ZEN-23151

---

README.mediawiki

Clarify Impact changes due to upgrade

---

ZenPacks/zenoss/LinuxMonitor/tests/utils.py

Set values to None in utils

---

ZenPacks/zenoss/LinuxMonitor/FileSystem.py

Fixes https://jira.zenoss.com/browse/ZEN-26032.
* Fix error message if NetApp filesystem referenced by Linux filesystem has been deleted
* Proper caching of NetApp NFS resources.

ZEN-26032: Handle deleted NetApp filesystems

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py

Fixes ZPS-644
* Make sure os_service plugin produces no stderr
* Log.debug unmapped output for debugging

Ensure modeler plugin has no stderr

---

README.html

Create html doc README.html

---

README.html
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py

Fixes ZPS-659
* Filter out errant unicode characters from systemctl output
* Improve regular expression matching for system process from systemctl

Improve OS process detection.

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Index hard disk disk_ids to allow fast search

---

ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py

Fixes ZPS-735
Add hard disk serial number and 30 bytes of uuid to
disk_ids to ease disk searching on CiscoUCS side.

Add additional entries to disk_ids

---

README.rst
ZenPacks/zenoss/LinuxMonitor/FileSystem.py

Fixes [ZPS-1006](https://jira.zenoss.com/browse/ZPS-1006).
The old one approach was broken due to recent ZPL updates.

ZPS-1006: Apply FileSystem_NFS_Client template to all NFS filesystems.

---

ZenPacks/zenoss/LinuxMonitor/FileSystem.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Fix DynamicView and Impact unit tests

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_release.py
ZenPacks/zenoss/LinuxMonitor/tests/testOSReleasePlugin.py

Improved OS Model parser for os_release modeler plugin.

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/df.py
ZenPacks/zenoss/LinuxMonitor/tests/test_modeler_df.py

Honor zFileSystemIgnoreTypes in df modeler plugin

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/interfaces.py

Fix "IndexError" modeling tun interfaces

---

ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Correct RPN in aliases

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/interfaces.py
ZenPacks/zenoss/LinuxMonitor/tests/test_modeler_interfaces_ip.py

Fixes ZPS-1695
* Process iproute (ip address) output in more modular way
* Add Unit tests for iproute processing

Modify processing of iproute interfaces

---

README.rst
ZenPacks/zenoss/LinuxMonitor/FileSystem.py

Fix issue with missing links between Linux and NetApp FileSystem components.

---

README.rst
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/os_service.py
ZenPacks/zenoss/LinuxMonitor/parsers/linux/service.py
ZenPacks/zenoss/LinuxMonitor/tests/testOSServicePlugin.py
ZenPacks/zenoss/LinuxMonitor/tests/test_serviceParser.py
ZenPacks/zenoss/LinuxMonitor/zenpack.yaml

Add support for Service Monitoring

---

ZenPacks/zenoss/LinuxMonitor/FileSystem.py
ZenPacks/zenoss/LinuxMonitor/HardDisk.py
ZenPacks/zenoss/LinuxMonitor/migrate/ReindexHardDisks.py

Fix linking events for FileSystem and HardDisk components

---

ZenPacks/zenoss/LinuxMonitor/parsers/linux/cpu.py

No docs needed for this. Feature added in this release.

Fixes nice cpu for 10+ cpus

---

README.rst
ZenPacks/zenoss/LinuxMonitor/migrate/AddModelerPlugins.py
ZenPacks/zenoss/LinuxMonitor/migrate/AddRelations.py
ZenPacks/zenoss/LinuxMonitor/modeler/plugins/zenoss/cmd/linux/lvm.py
ZenPacks/zenoss/LinuxMonitor/tests/plugindata/lvm.py

Fixes ZPS-3411
* Enhance migration scripts remove old modeler plugins
* Remove uneeded empty relations
* Change metatypesize to type int

Fix various modeling issues for 2.3.0

---

README.rst
ZenPacks/zenoss/LinuxMonitor/parsers/linux/cpu.py

Fix CPU Busy metric on "CPU Utilization" graph.
